### PR TITLE
[fdsnws] implement request log for dataselect

### PR DESCRIPTION
**Pull request by andres-h**
Implement file-based (JSON) request log that is easier handle than "reqtrack" database and may help with GDPR compliance.

### CODE REVIEW

**Comment by gempa-jabe** [comment]
Thanks @andres-h for the implementation. Can you please elaborate a bit more about how that works and add how it complements or replaces the current trackdb? Also the documentation needs an update with respect to that feature.

* Which files does it produce?
* How are they supposed to be used?

Thank you.

**Comment by andres-h** [comment]
Documentation added.

**Comment by gempa-jabe** [comment]
Thank you @andres-h, that is looking great. I ask @gempa-stephan to check the PR before merging it.

**Comment by gempa-stephan** [comment]
I would suggest to define a common base class both Tracker implementations derive from.

Also the new dependencies, e.g. GeoIP, introduced by the JSON implementation should be documented.

**Comment by andres-h** [comment]
> I would suggest to define a common base class both Tracker implementations derive from.

There is no common code, so the base class would have to be abstract, which is not so useful in Python. I think it would be helpful to have a proxy class that encapsulates trackerList. Something like we had in ArcLink (but hopefully without eval): https://github.com/SeisComP3/seiscomp3/blob/b55092803f077c9a72758c7cb1ad7bd032f58370/src/arclink/libs/python/seiscomp/arclink/handler.py#L521

**Pull request merged**
