### PR TITLE
Hypo71 max phases set to 1001

### PR DESCRIPTION
**Pull request by gempa-jabe**
This PR includes two changes:

* Increase maximum phase number to 1001
* Raise an error if a profile does not include a velocity model
* Fix bug which re-uses the velocity model if a profile has changed to one which does not include a velocity model

### CODE REVIEW

**Comment by gempa-jabe** [comment]
@jmsaurel, please double-check.

**Comment by jmsaurel** [comment]
- Maximum number of phases increase shouldn't cause any issue according to an Hypo71 specialist colleague
- Ok for error raised when no velocity model found
- Ok for the bug fix

Could you add a check that verify Tvelocity and Tdepth contains the same number of values and raise an otherwise ?
`number of velocities and number of depth layers should be identical`

**Comment by gempa-jabe** [comment]
> Could you add a check that verify Tvelocity and Tdepth contains the same number of values and raise an otherwise ?

The check you request is already there, see https://github.com/SeisComP3/seiscomp3/blob/e8bf070bfcd240ca1fc8a28a8d0e4ce8acacdf5d/src/ipgp/plugins/locator/hypo71/hypo71.cpp#L2363. Do we need to change that?

**Comment by jmsaurel** [comment]
> > Could you add a check that verify Tvelocity and Tdepth contains the same number of values and raise an otherwise ?
> 
> The check you request is already there, see
> 
> [seiscomp3/src/ipgp/plugins/locator/hypo71/hypo71.cpp](https://github.com/SeisComP3/seiscomp3/blob/e8bf070bfcd240ca1fc8a28a8d0e4ce8acacdf5d/src/ipgp/plugins/locator/hypo71/hypo71.cpp#L2363)
> 
> Line 2363 in [e8bf070](/SeisComP3/seiscomp3/commit/e8bf070bfcd240ca1fc8a28a8d0e4ce8acacdf5d)
>  if ( Tvelocity.size() != Tdepth.size() ) 
> . Do we need to change that?

Sorry, I didn't saw it.
No need to change it.

So it's ok for this pull request

**Pull request merged**
