### PR TITLE
Improvement of the conversion stylesheet scml/qml

### PR DESCRIPTION
**Pull request by FMassin**
> (used in filters) is invalide qml symbol, they are substituted with empty space.

### CODE REVIEW

**Comment by gempa-jabe** [comment]
Can you please apply the diffs only and not replacing the entire file? I haven't checked why the whole file was replaced but maybe it has something to do with newlines. With the current commits we cannot easily track the changes you applied. Thank you.

**Comment by ccauzzi** [comment]
Thanks for the feedback on the right usage Jan, this is the change we made:


  <xsl:template name="valueOfIDNode">
      <xsl:call-template name="convertOptionalID">
          <xsl:with-param name="id" select="translate(., '&gt;', '')"/>
      </xsl:call-template>
  </xsl:template>

to avoid having “>” symbols that are not allowed in qml,
Carlo.

______________________________________

Schweizerischer Erdbebendienst
ETH Zürich

Dr. Carlo Cauzzi
NO FO 69.7
Sonneggstrasse 5
8092 Zürich
Schweiz

phone: +41-44-6339161
carlo.cauzzi@sed.ethz.ch
http://www.seismo.ethz.ch/research/groups/alrt
______________________________________

**Comment by gempa-jabe** [comment]
Thanks Carlo, that helps. Did you edit the file with MS Windows tools? With hexedit I see that newlines are \r\n instead of just \n. That explains the huge diff.

**Comment by ccauzzi** [comment]
I used Terminal on MAC OS, sorry if this has created some confusion with the newlines.

The whole modification boils down to commenting some lines of code from Herrnkind:

 


and appending immediately after the modified version (where I copied one line from an xsl of Enrico Ballarin)

    
    <xsl:template name="valueOfIDNode">
        <xsl:call-template name="convertOptionalID">
            <xsl:with-param name="id" select="translate(., '&gt;', '')"/>
        </xsl:call-template>
    </xsl:template>


Nothing else. Thanks, ciao,
Carlo
______________________________________

Schweizerischer Erdbebendienst
ETH Zürich

Dr. Carlo Cauzzi
NO FO 69.7
Sonneggstrasse 5
8092 Zürich
Schweiz

phone: +41-44-6339161
carlo.cauzzi@sed.ethz.ch
http://www.seismo.ethz.ch/research/groups/alrt
______________________________________

**Comment by FMassin** [comment]
Jumping in late, sorry. 
I corrected the carriage returns (`s/^M//`). Is there more things you can comment Carlo (@ccauzzi) ?

**Pull request merged**
