### PR TITLE
waits until the time of the last data point in record has been reached

### PR DESCRIPTION
**Pull request by raciner**
msrtsimul now waits until the timestamp of the last data point in the record has been reached instead of the first.

### CODE REVIEW

**Comment by raciner** [comment]
Thank you for pointing this out, it should now be fixed.

**Comment by gempa-jabe** [comment]
If I can now ask you to squash your commits I will test and merge it ;)

**Comment by raciner** [comment]
Done.

**Comment by gempa-jabe** [comment]
I merge it but had to fix the seedlink setup handler and the mseedfifo setup. I will add this as an additional commit.

**Pull request merged**
