### PR TITLE
[scolv] Initial spectrogram implementation

### PR DESCRIPTION
**Pull request by gempa-jabe**
This implements a spectrogram layer in the manual picker window. The spectrogram view can be toggled with ctrl+s and is by default off. A new toolbar has been added as well to configure the spectrogram, in particular spectra window length and window overlap.
Ping @marcopovitch.

### CODE REVIEW

**Comment by marcopovitch** [comment]
on osx > 10.9 exp10 has to be called with __exp10.

**Comment by gempa-jabe** [comment]
I replaced the GNU extensions with standard pow calls. That should also compile on OSX.

**Comment by gempa-jabe** [comment]
@marcopovitch Any updates? Does it work?

**Comment by marcopovitch** [comment]
@gempa-jabe it works, but I haven't yet fully tested it. I need a couple of days to give you some feedbacks.

**Pull request merged**
