### PR TITLE
[DatabaseArchive] make OID 64-bit

### PR DESCRIPTION
**Pull request by andres-h**

### CODE REVIEW

**Comment by gempa-jabe** [comment]
Thanks for the PR, @andres-h.

**Comment by gempa-jabe** [comment]
Note that the changes will break binary compatibility with existing releases so we need to create a new release with that patch.

**Comment by Jollyfant** [comment]
Thanks! We should not forget to update the .sql too to BIGINT.

**Comment by gempa-jabe** [comment]
I added a branch (oid64) in this repository with the revised patch, the database changes and Python wrapper updates. What is missing is a migration script for MySQL and SQLite3. PostgreSQL already uses BIGINT for oid and parent_oid. Since the schema itself hasn't changed, we cannot use another schema version for it. Furthermore, since the code supports 64bit ids the conversion to BIGINT is optional and not necessary. It will also work with INTEGER ids. It is up to the operator to convert the tables or not. New users will start with BIGINT though.

**Comment by gempa-jabe** [comment]
@Jollyfant, are there any updates regarding that issue? Have the fixes resolved your issue?

**Comment by Jollyfant** [comment]
I have not updated the version but replaced by database with a new one still using the 32-bit limit.

**Comment by gempa-jabe** [comment]
The maintained branch for that feature is oid64 in this repository. Therefore this PR will be closed and a new one will be opened.

**Pull request closed without merging**
