### PR TITLE
EIDA fdsnws developments

### PR DESCRIPTION
**Pull request by andres-h**
* request statistics (reqtrack)
* access to restricted data (auth extension)
* fdsnws_fetch utility

### CODE REVIEW

**Comment by gempa-jabe** [comment]
Can you please squash commits that implement one feature? E.g. a63d366 and 97c4af3 can be squashed. If the bugfix commit does belong to another commit of this PR, please squash it as well. Thank you.

**Comment by andres-h** [comment]
OK, I've done a rebase, but currently I don't have write permission to EIDA/seiscomp3. Trying to resolve this.

**Comment by andres-h** [comment]
It is force-pushed now.

**Comment by gempa-jabe** [comment]
Thank you! Merged

**Pull request merged**
